context:
  version: "0.1.5"
  python_min: "3.10"

package:
  name: mxbai-rerank
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/mxbai-rerank/mxbai_rerank-${{ version }}.tar.gz
    sha256: 2dd0f148288f2322ddc217ce27ec77fdfea4fc6ac26e7d4f026c2eba41145c98

build:
  number: 1
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - transformers >=4.49.0
    - pytorch >=2.0.0
    - numpy >=1
    - batched >=0.1.4
    - tqdm >=4.67.1
    - accelerate >=1.5.1

tests:
  - python:
      imports:
        - mxbai_rerank
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Crispy reranking models from Mixedbread.
  homepage: https://github.com/mixedbread-ai/mxbai-rerank
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://mixedbread.com/blog/mxbai-rerank-v2

extra:
  recipe-maintainers:
    - moritzwilksch
